I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1574, in script call
    call saturday1
  File "game/branc.rpy", line 293, in script
    extned "\n내게 쏟아지던 것은 제각각 다른 종류의 시선이었으나. {w}결과적으로는 모두 같은 의미를 내포하고 있었다."
Exception: Sayer 'extned' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1574, in script call
    call saturday1
  File "game/branc.rpy", line 293, in script
    extned "\n내게 쏟아지던 것은 제각각 다른 종류의 시선이었으나. {w}결과적으로는 모두 같은 의미를 내포하고 있었다."
  File "renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'extned' is not defined.

Windows-10-10.0.22000
Ren'Py 7.4.11.2266
 
Wed Mar 16 20:47:04 2022
