I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1565, in script
    call screen schedule
  File "renpy/common/000statements.rpy", line 569, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
TypeError: __call__() got an unexpected keyword argument 'new_widget'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1565, in script
    call screen schedule
  File "renpy/ast.py", line 2015, in execute
    self.call("execute")
  File "renpy/ast.py", line 2003, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "renpy/statements.py", line 278, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 569, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "renpy/exports.py", line 3136, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "renpy/display/core.py", line 3325, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "renpy/display/core.py", line 3676, in interact_core
    new_widget=layers_root)
TypeError: __call__() got an unexpected keyword argument 'new_widget'

Windows-10-10.0.22000
Ren'Py 7.4.11.2266
 
Wed Mar 16 15:57:44 2022
