I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 729, in script
    if len(wehre_list) > 5:
  File "game/script.rpy", line 729, in <module>
    if len(wehre_list) > 5:
NameError: name 'wehre_list' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 729, in script
    if len(wehre_list) > 5:
  File "C:\Users\jaejun\Downloads\renpy-7.3.5-sdk/renpy/ast.py", line 1898, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\jaejun\Downloads\renpy-7.3.5-sdk/renpy/python.py", line 2276, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\jaejun\Downloads\renpy-7.3.5-sdk/renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 729, in <module>
    if len(wehre_list) > 5:
NameError: name 'wehre_list' is not defined

Windows-10-10.0.18362
Ren'Py 7.4.11.2266
Tale of the corporal 1.0
Fri Feb 18 23:36:50 2022
